name: build and upload s3

on:
  push:
    branches:
      - main

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: 저장소 체크아웃
        uses: actions/checkout@v4.1.1

      - name: Node.js 설정
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: npm install
        run: npm install

      - name: npm run build
        run: npm run build

      - name: Upload S3
        # You may pin to the exact commit or the version.
        # uses: shallwefootball/upload-s3-action@4350529f410221787ccf424e50133cbc1b52704e
        uses: shallwefootball/upload-s3-action@v1.3.3
        with:
          # aws key id
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          # aws secret access key
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # aws bucket name
          aws_bucket: ${{ secrets.AWS_S3_BUCKET }}
          
          # 업로드할 로컬 디렉토리 경로를 지정합니다.
          source_dir: ./dist/
          
          # S3 Bucket의 목적지 디렉토리 경로를 지정합니다. (선택 사항, 기본값은 /)
          destination_dir: ./ # optional, default is /
          
          # s3의 엔드포인트를 url로 저장
          #endpoint: # optional


      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # AWS 리전을 본인의 리전으로 변경하세요.

      - name: Create CloudFront Invalidation
        run: |
          aws cloudfront create-invalidation \
            --distribution-id EHL9N63SHSY32 \
            --paths "/*"